default['mysql']['client']="https://s3-us-west-1.amazonaws.com/srikanth8/Mysql/MySQL-client-5.6.el6.rpm"
default['mysql']['server']="https://s3-us-west-1.amazonaws.com/srikanth8/Mysql/MySQL-server-5.6.el6.rpm"
default['mysql']['devel']="https://s3-us-west-1.amazonaws.com/srikanth8/Mysql/MySQL-devel-5.6.el6.rpm"
default['mysql']['port']="3306"
default['mysql']['config_dir']="/opt"
